### ISSUE TITLE
Firefox 67 not identified

### ISSUE THREAD

**Issue by izikaj** [yankouskia/is-incognito-mode#2]
In normal mode and incognito showing same "unrecognized" message
Browser: Firefox 67 (64bits)
Platform: macOS
Result: 
> I am really unable to identify incognito mode!
> Sorry for that ...

**Comment by igorkamyshev** [comment]
Same.

**Comment by yankouskia** [comment]
@IzikAJ @igorkamyshev Thank you for reporting. Could you please try again with the latest version?

**Comment by igorkamyshev** [comment]
@yankouskia now I have this issue on demo site. 😔

<img width="1552" alt="Screenshot 2019-05-29 at 11 10 12" src="https://user-images.githubusercontent.com/26767722/58540650-7c643c00-8202-11e9-8cc9-49a6f8534771.png">

**Comment by yankouskia** [comment]
hmm, that's weird ...
@igorkamyshev post please your `useragent`. I will be able to figure out what is going wrong
